import { type z } from "zod";
import { type dbSeedSchema } from "./dbSeed";

export const internationalizationData: z.infer<typeof dbSeedSchema> = {
  committees: [
    {
      name: "Internacionalização da Amazônia",
      countries: [
        {
          name: "Associação de Defesa Etnoambiental Kanindé",
          shortName: "Associação Kanindé",
          flag: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fgoaround-img.s3-sa-east-1.amazonaws.com%2F4b2cf468-0c8a-49cb-859a-dcd08e4be18d%2Fd9089d34-6991-471a-bc01-58b115b84263.thumb.jpg&f=1&nofb=1&ipt=504aafe01748cb42f0f02ac62664a512f1113ac39b92264dcbc674ccba855b74&ipo=images",
          delegates: [
            { code: "ADK1", name: "Ivandeide Bandeira Cardozo" },
            { code: "ADK2", name: "Txai Suruí" },
          ],
        },
        {
          name: "Canadá",
          flag: "https://flagcdn.com/h40/ca.png",
          delegates: [
            { code: "CA1", name: "Mr. Christopher Thornley" },
            { code: "CA2", name: "Mr. Robert Bunbury" },
          ],
        },
        {
          name: "Estado do Japão",
          flag: "https://flagcdn.com/h40/jp.png",
          delegates: [
            { code: "JP1", name: "Mr. KITAGAWA Yasuhisa" },
            { code: "JP2", name: "Mr. Okaniwa Ken" },
          ],
        },
        {
          name: "Estado Plurinacional da Bolívia",
          shortName: "Bolívia",
          flag: "https://flagcdn.com/h40/bo.png",
          delegates: [
            { code: "BO1", name: "Sr. Juan Santos Cruz" },
            { code: "BO2", name: "Sra. Magda Infantes" },
          ],
        },
        {
          name: "Estados Unidos da América",
          shortName: "Estados Unidos",
          flag: "https://flagcdn.com/h40/us.png",
          delegates: [
            { code: "US1", name: "Mr. Bill Lehmberg" },
            { code: "US2", name: "Mr. James Mosher" },
          ],
        },
        {
          name: "Federação da Rússia",
          shortName: "Rússia",
          flag: "https://flagcdn.com/h40/ru.png",
          delegates: [
            { code: "RU1", name: "Ms. Galina Bublikova" },
            { code: "RU2", name: "Mr. Dmitry Maksimychev" },
          ],
        },
        {
          name: "Funai",
          flag: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fescolaeducacao.com.br%2Fwp-content%2Fuploads%2F2019%2F04%2Ffunai.jpg&f=1&nofb=1&ipt=eada369a9f49aa7b7cb6efe0617a3eb933c23c7093a5d927bfe42e7c9abcfe53&ipo=images",
          delegates: [
            { code: "FU1", name: "Joenia Wapichana" },
            { code: "FU2", name: "Maria Janete Albuquerque de Carvalho" },
          ],
        },
        {
          name: "Fundação Gaia Amazonas",
          shortName: "Gaia Amazonas",
          flag: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.vimeocdn.com%2Fportrait%2F39115875_640x640&f=1&nofb=1&ipt=0e7fef54017d9e1ea36030b2a84aacb0a736a2a620b392478052eceb5227d4c1&ipo=images",
          delegates: [
            { code: "GA1", name: "Martín von Hildebrand" },
            { code: "GA2", name: "Lara Lutzenberger" },
          ],
        },
        {
          name: "Guiana Francesa",
          flag: "https://flagcdn.com/h40/gf.png",
          delegates: [
            { code: "GF1", name: "Ms. Galina Bublikova" },
            { code: "GF2", name: "Mr. Dmitry Maksimychev" },
          ],
        },
        {
          name: "Ibama",
          flag: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.geosenso.com.br%2Fwp-content%2Fuploads%2F2015%2F06%2Fgeosenso-legisla%25C3%25A7%25C3%25A3o-federal-ibama.png&f=1&nofb=1&ipt=595ed0bb25a2f54e1d560c33efc4cf0f8e1e44611843631e730c5e344afb5f79&ipo=images",
          delegates: [
            { code: "IB1", name: "Rodrigo Agostinho" },
            { code: "IB2", name: "Edel Moraes" },
          ],
        },
        {
          name: "INCRA",
          flag: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fansinfo.net.br%2Fansagrimensurav2%2Fwp-content%2Fuploads%2F2017%2F12%2Fincra-logo.jpg&f=1&nofb=1&ipt=b82a8da07a39aba90de3a6b3db2d0caae40738a172ecf6931b8715fcd9a1e6a5&ipo=images",
          delegates: [
            {
              code: "IN1",
              name: "Gustavo Souto de Noronha Maria Rosilene Bezerra Rodrigues",
            },
            {
              code: "IN2",
              name: "Geraldo José da Camara Ferreira de Melo Filho",
            },
          ],
        },
        {
          name: "Reino da Noruega",
          shortName: "Noruega",
          flag: "https://flagcdn.com/h40/no.png",
          delegates: [
            { code: "NO1", name: "Mr. Gunnar Andreas Holm" },
            { code: "NO2", name: "Mr. Øystein Størkersen" },
          ],
        },
        {
          name: "Reino Unido da Grã-Bretanha e Irlanda do Norte",
          shortName: "Reino Unido",
          flag: "https://flagcdn.com/h40/gb.png",
          delegates: [
            { code: "UK1", name: "Ms Josephine Gauld " },
            { code: "UK2", name: "Ms. Anita Siro" },
          ],
        },
        {
          name: "República Bolivariana da Venezuela",
          shortName: "Venezuela",
          flag: "https://flagcdn.com/h40/ve.png",
          delegates: [
            { code: "VE1", name: "Mr. Jesus Manzanilla" },
            { code: "VE2", name: "Mrs. Liukza Lorena Hernandez Faria" },
          ],
        },
        {
          name: "República da Colômbia",
          shortName: "Colômbia",
          flag: "https://flagcdn.com/h40/co.png",
          delegates: [
            { code: "CO1", name: "Mr. Rafael Jose Medina Whitaker" },
            { code: "CO2", name: "Mr. Sergio Salazar Alzate" },
          ],
        },
        {
          name: "República do Equador",
          shortName: "Equador",
          flag: "https://flagcdn.com/h40/ec.png",
          delegates: [
            { name: " Mr. Alejandro Davalos", code: "EQ1" },
            { name: "Ms. Andrea Olmedo", code: "EQ2" },
          ],
        },
        {
          name: "República do Peru",
          shortName: "Peru",
          flag: "https://flagcdn.com/h40/pe.png",
          delegates: [
            { name: "Mr. Luis Chuquihuara Chil", code: "PE1" },
            { name: "Mrs. Ana Maria Fanny Ruiz Aranbar", code: "PE2" },
          ],
        },
        {
          name: "República do Suriname",
          shortName: "Suriname",
          flag: "https://flagcdn.com/h40/sr.png",
          delegates: [
            { name: "Ms. Ivette Patterzon", code: "SR1" },
            { name: "Mr. Sylvano Tjong-Ahin", code: "SR2" },
          ],
        },
        {
          name: "República Federal da Alemanha",
          shortName: "Alemanha",
          flag: "https://flagcdn.com/h40/de.png",
          delegates: [
            { name: "Mr. Martin Röw", code: "DE1" },
            { name: "Mr. Sebastian Groth", code: "DE2" },
          ],
        },
        {
          name: "República Federativa do Brasil",
          shortName: "Brasil",
          flag: "https://flagcdn.com/h40/br.png",
          delegates: [
            { name: "Ms. Tatiana Gomes Bustamante", code: "BR1" },
            { name: "Mr. Silvio Jose Albuquerque e Silva", code: "BR2" },
          ],
        },
        {
          name: "República Francesa",
          shortName: "França",
          flag: "https://flagcdn.com/h40/fr.png",
          delegates: [
            { name: "Mr. Arnaud Suquet ", code: "FR1" },
            { name: "Mr. Clément PAYEUR", code: "FR2" },
          ],
        },
        {
          name: "República Italiana",
          shortName: "Itália",
          flag: "https://flagcdn.com/h40/it.png",
          delegates: [
            { name: "Mr. Roberto Natali", code: "IT1" },
            { name: "Mr. Giacomo Montemarani", code: "IT2" },
          ],
        },
        {
          name: "Survival International",
          flag: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.guiaongs.org%2Fwp-content%2Fuploads%2F2015%2F09%2FSURVIVAL-360x336.jpg&f=1&nofb=1&ipt=4fa8d3cc52b5c4aa89f4704ac0e2abe718d860b112ef750376fe9cc952aeb958&ipo=images",
          delegates: [
            { name: "Mr. Robin Hanbury-Tenison", code: "SI1" },
            { name: "Mr. Stephen Corry", code: "SI2" },
          ],
        },
        {
          name: "WWF",
          flag: "https://cdnassets.panda.org/_skins/international/img/logo.png",
          delegates: [
            { name: "Mr. Maurício de Almeida Voivodic", code: "WWF1" },
            { name: "Ms. Gabriela Yamaguchi", code: "WWF2" },
          ],
        },
      ],
    },
  ],
};

export const judicializationData: z.infer<typeof dbSeedSchema> = {
  committees: [
    {
      name: "Judicialização da Política",
      countries: [
        {
          country: "Nikolas Ferreira (PL)",
          delegado: "Lucas Duran",
          code: "PL1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Logomarca_Partido_Liberal_%28Brasil%29.svg/1920px-Logomarca_Partido_Liberal_%28Brasil%29.svg.png",
          delegate: "Nikolas Ferreira",
          party: "PL",
          number: "1",
        },
        {
          country: "Carla Zambelli (PL)",
          delegado: "Julia Darini",
          code: "PL2",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Logomarca_Partido_Liberal_%28Brasil%29.svg/1920px-Logomarca_Partido_Liberal_%28Brasil%29.svg.png",
          delegate: "Carla Zambelli",
          party: "PL",
          number: "2",
        },
        {
          country: "Eduardo Bolsonaro (PL)",
          delegado: "Bruno Zimmermann Russo Ferreira",
          code: "PL3",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Logomarca_Partido_Liberal_%28Brasil%29.svg/1920px-Logomarca_Partido_Liberal_%28Brasil%29.svg.png",
          delegate: "Eduardo Bolsonaro",
          party: "PL",
          number: "3",
        },
        {
          country: "Ricardo Salles (PL)",
          delegado: "João Vinicius Paes de Figueiredo",
          code: "PL4",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Logomarca_Partido_Liberal_%28Brasil%29.svg/1920px-Logomarca_Partido_Liberal_%28Brasil%29.svg.png",
          delegate: "Ricardo Salles",
          party: "PL",
          number: "4",
        },
        {
          country: "André Ferreira (PL)",
          delegado: "João Pedro Gesteira Costa Pinto de Campos",
          code: "PL5",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Logomarca_Partido_Liberal_%28Brasil%29.svg/1920px-Logomarca_Partido_Liberal_%28Brasil%29.svg.png",
          delegate: "André Ferreira",
          party: "PL",
          number: "5",
        },
        {
          country: "Filipe Barros (PL)",
          delegado: "Nicollas Saab",
          code: "PL6",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Logomarca_Partido_Liberal_%28Brasil%29.svg/1920px-Logomarca_Partido_Liberal_%28Brasil%29.svg.png",
          delegate: "Filipe Barros",
          party: "PL",
          number: "6",
        },
        {
          country: "Kim Kataguiri (UNIÃO)",
          delegado: "Francisco Carazzato Maciel",
          code: "UNIÃO1",
          flag: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsulnoticias.com%2Fwp-content%2Fuploads%2F2022%2F02%2FUniao_Brasil_logo.svg_.png&f=1&nofb=1&ipt=341165375d6e6c72c972471d56f069de5c9fe303b8c8ca3bef154eb8f88e27be&ipo=images",
          delegate: "Kim Kataguiri",
          party: "UNIÃO",
          number: "1",
        },
        {
          country: "Silvye Alves (UNIÃO)",
          delegado: "Maria Luiza Gimenez Waller Nascimento",
          code: "UNIÃO2",
          flag: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsulnoticias.com%2Fwp-content%2Fuploads%2F2022%2F02%2FUniao_Brasil_logo.svg_.png&f=1&nofb=1&ipt=341165375d6e6c72c972471d56f069de5c9fe303b8c8ca3bef154eb8f88e27be&ipo=images",
          delegate: "Silvye Alves",
          party: "UNIÃO",
          number: "2",
        },
        {
          country: "Marcel Van Hattem (NOVO)",
          delegado: "Felipe D ́Albuquerque Andrade Da Silveira",
          code: "NOVO1",
          flag: "https://instagram.fcgh12-1.fna.fbcdn.net/v/t51.2885-19/241857992_309311260967271_4056941430220595171_n.jpg?stp=dst-jpg_s320x320&_nc_ht=instagram.fcgh12-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=5CiNnihlZU8AX9waM3H&edm=AOQ1c0wBAAAA&ccb=7-5&oh=00_AfC-J0SPLiFEeQJZoNH9nbDvSk35KPSvsHHAVfdbgZaMjw&oe=643A6D75&_nc_sid=8fd12b",
          delegate: "Marcel Van Hattem",
          party: "NOVO",
          number: "1",
        },
        {
          country: "Adriana Ventura (NOVO)",
          delegado: "Sophia Lages De Altavila Harris",
          code: "NOVO2",
          flag: "",
          delegate: "Adriana Ventura",
          party: "NOVO",
          number: "2",
        },
        {
          country: "Bruno Lima (PP)",
          delegado: "Catarina Evrard de Mello",
          code: "PP1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Progressistas_logo.png/440px-Progressistas_logo.png",
          delegate: "Bruno Lima",
          party: "PP",
          number: "1",
        },
        {
          country: "Arthur Lira (PP)",
          delegado: "Maria Luisa Cilento Morsello",
          code: "PP2",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Progressistas_logo.png/440px-Progressistas_logo.png",
          delegate: "Arthur Lira",
          party: "PP",
          number: "2",
        },
        {
          country: "Deltan Dallagnol (PODE)",
          delegado: "Pedro Tasso Botkowski",
          code: "PODE1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/PODEMOSLogo.png/360px-PODEMOSLogo.png",
          delegate: "Deltan Dallagnol",
          party: "PODE",
          number: "1",
        },
        {
          country: "Fábio Macedo (PODE)",
          delegado: "Roberto Herbella Maia",
          code: "PODE2",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/PODEMOSLogo.png/360px-PODEMOSLogo.png",
          delegate: "Fábio Macedo",
          party: "PODE",
          number: "2",
        },
        {
          country: "Celso Russomanno (REPUBLICANOS)",
          delegado: "Rafael Renyi Lintz",
          code: "REPUBLICANOS1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Republicanosbrasil.png/440px-Republicanosbrasil.png",
          delegate: "Celso Russomanno",
          party: "REPUBLICANOS",
          number: "1",
        },
        {
          country: "Tenente Coronel Zucco (REPUBLICANOS)",
          delegado: "Gabriel Achcar Aigner-Torres",
          code: "REPUBLICANOS2",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Republicanosbrasil.png/440px-Republicanosbrasil.png",
          delegate: "Tenente Coronel Zucco",
          party: "REPUBLICANOS",
          number: "2",
        },
        {
          country: "Dra. Alessandra Haber (MDB)",
          delegado: "Sophia Rosa Pulino",
          code: "MDB1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Movimento_Democr%C3%A1tico_Brasileiro_%282017%29.png/400px-Movimento_Democr%C3%A1tico_Brasileiro_%282017%29.png",
          delegate: "Dra. Alessandra Haber",
          party: "MDB",
          number: "1",
        },
        {
          country: "Delegado Palumbo (MDB)",
          delegado: "Laura Villani Gama",
          code: "MDB2",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Movimento_Democr%C3%A1tico_Brasileiro_%282017%29.png/400px-Movimento_Democr%C3%A1tico_Brasileiro_%282017%29.png",
          delegate: "Delegado Palumbo",
          party: "MDB",
          number: "2",
        },
        {
          country: "Amom Mandel (CIDADANIA)",
          delegado: "Regina Evrard de Mello",
          code: "CIDADANIA1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Logo_do_Cidadania_23.png",
          delegate: "Amom Mandel",
          party: "CIDADANIA",
          number: "1",
        },
        {
          country: "Alex Manente (CIDADANIA)",
          delegado: "Bruna Cursino Lourenço",
          code: "CIDADANIA2",
          flag: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Logo_do_Cidadania_23.png",
          delegate: "Alex Manente",
          party: "CIDADANIA",
          number: "2",
        },
        {
          country: "Tabata Amaral (PDT)",
          delegado: "Caroline Rodolpho Ferreira",
          code: "PDT1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/LogoPDT.svg/400px-LogoPDT.svg.png",
          delegate: "Tabata Amaral",
          party: "PDT",
          number: "1",
        },
        {
          country: "Erika Hilton (PSOL)",
          delegado: "Olivia Pinho de Souza",
          code: "PSOL1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Psol_ziraldo.png/500px-Psol_ziraldo.png",
          delegate: "Erika Hilton",
          party: "PSOL",
          number: "1",
        },
        {
          country: "Guilherme Boulos (PSOL)",
          delegado: "Júlia Vitelli Morgado",
          code: "PSOL2",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Psol_ziraldo.png/500px-Psol_ziraldo.png",
          delegate: "Guilherme Boulos",
          party: "PSOL",
          number: "2",
        },
        {
          country: "Gleisi (PT)",
          delegado: "Pietra Marra Canova",
          code: "PT1",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PT_%28Brazil%29_logo_2021.svg/300px-PT_%28Brazil%29_logo_2021.svg.png",
          delegate: "Gleisi",
          party: "PT",
          number: "1",
        },
        {
          country: "Zeca Dirceu (PT)",
          delegado: "Mariana Quinta Cunha",
          code: "PT2",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PT_%28Brazil%29_logo_2021.svg/300px-PT_%28Brazil%29_logo_2021.svg.png",
          delegate: "Zeca Dirceu",
          party: "PT",
          number: "2",
        },
        {
          country: "Rui Falcão (PT)",
          delegado: "Ilana Ferrari Nato",
          code: "PT3",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PT_%28Brazil%29_logo_2021.svg/300px-PT_%28Brazil%29_logo_2021.svg.png",
          delegate: "Rui Falcão",
          party: "PT",
          number: "3",
        },
        {
          country: "Jorge Solla (PT)",
          delegado: "Mayara Pães Horácio Ferreira Caetano",
          code: "PT4",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PT_%28Brazil%29_logo_2021.svg/300px-PT_%28Brazil%29_logo_2021.svg.png",
          delegate: "Jorge Solla",
          party: "PT",
          number: "4",
        },
        {
          country: "Margarida Salomão (PT)",
          delegado: "Luisa Montani Fernandes",
          code: "PT5",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PT_%28Brazil%29_logo_2021.svg/300px-PT_%28Brazil%29_logo_2021.svg.png",
          delegate: "Margarida Salomão",
          party: "PT",
          number: "5",
        },
        {
          country: "João Daniel (PT)",
          delegado: "Maria Eduarda da Cunha Pacces",
          code: "PT6",
          flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/PT_%28Brazil%29_logo_2021.svg/300px-PT_%28Brazil%29_logo_2021.svg.png",
          delegate: "João Daniel",
          party: "PT",
          number: "6",
        },
      ].map(({ country, code, flag, delegado }) => ({
        name: country,
        flag,
        delegates: [
          {
            name: delegado,
            code,
          },
        ],
      })),
    },
  ],
};
